Rename overlaycall/overlaydata to overlay_call/overlay_data
riscv-software-src/riscv-overlay pull request #32
Opened 2021-11-15 11:12 UTC by edward-jones

This updates the name of the overlay attribute names to make
them more readable.

2021-11-15 11:22 UTC, oferShinaar reviewed
Please add a note explaining how you tested the RT Eng

2021-11-15 13:11 UTC, nidalf approved these changes

2021-11-16 06:26 UTC, oferShinaar requested changes
please check the comments

2021-11-23 19:18 UTC, craigblackmore approved these changes
LGTM once Ofer's comments have been addressed.

2021-11-29 12:44 UTC, edward-jones commented
I've separated out the change to the runtime engine into #36

2021-11-30 06:16 UTC, oferShinaar commented
due to PR #36, we can merge and close this

2021-11-30 06:16 UTC, merged

2021-11-30 06:16 UTC, oferShinaar commented
due to PR #36, we can merge and close this